# sqp_f24fe3dc6557611d13db76f464be6b517c5eb5b4

default:
  image: maven:3.8.2-openjdk-11

variables:
  M2_EXTRA_OPTIONS: "-s .m2/settings.xml"
  IMAGE_NAME: spring-petclinic
  
stages:
  - check
  - build
  - sonarscan
  - push
  - dockerize
  - deploy

.check-version:
  stage: check
  script:
    - mvn --version

.build-job:
  stage: build
  script:
    - echo "Building the WAR file"
    - mvn package
    - ls -l target/*.war
  artifacts:
    paths:
      - target/
    expire_in: 1 week

.sonarscan:
  stage: sonarscan
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    SONAR_HOST_URL: http://174.138.104.191:9000
    SONAR_TOKEN: sqp_f24fe3dc6557611d13db76f464be6b517c5eb5b4
  image:
    name: sonarsource/sonar-scanner-cli:latest
  script:
   - sonar-scanner -Dsonar.qualitygate.wait=true

.push-to-nexus:
  stage: push
  script:
    - mvn $M2_EXTRA_OPTIONS deploy

.dockerize:
  stage: dockerize
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker login -u $USERNAME -p $PASSWORD
  script:
    - docker build -t $USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA .
    - docker tag $USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA $USERNAME/$IMAGE_NAME:latest
    - docker push $USERNAME/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $USERNAME/$IMAGE_NAME:latest

deploy-to-kubernetes:
  stage: deploy
  image: 
    name: kunchalavikram/kubectl_helm_cli:latest  # Helm
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube
    - cat "$KUBECONFIG" > ~/.kube/config 
  script:
    - helm upgrade --install petclinic petclinic-chart/

